.TH kopano\-storeadm 8 "2018-01-11" "Kopano 8" "Kopano Groupware Core reference"
.SH Name
kopano\-storeadm \(em store management utility
.SH Synopsis
\fBkopano\-storeadm\fP \fB\-C\fP [\fB\-c\fP \fIfile\fP] [\fB\-h\fP \fIuri\fP]
[\fB\-k\fP \fIcompany\fP] [\fB\-n\fP \fIname\fP]
.SH Description
.PP
This tool is used to manage message stores on the Kopano server. Specifically,
it allows to create, delete, attach, detach such stores. The storage server
must be running for kopano-storeadm to work.
.SH Options
.TP
\fB\-C\fP
Create a new store and attach it to the user account specified with \fB\-n\fP.
That account must not have an associated store yet.
.TP
\fB\-c\fP \fIfile\fP
Read config file.
.TP
\fB\-h\fP \fIuri\fP
Specify an alternate URI for connecting to a Kopano server.
.TP
\fB\-n\fP \fIentity-name\fP
For \fB\-C\fP and \fB\-D\fP, specifies the user to work on.
.TP
\fB\-t\fP {\fBuser\fP|\fBarchive\fP|\fBgroup\fP|\fBcompany\fP}
The store type for the entity specified with \fB\-n\fP. If not specified,
\fB\-t user\fP is implicitly assumed.
.SH Examples
.IP \(bu 4
Create new store for user: kopano\-storeadm \-Cn user1
.SH Configuration file
.PP
Normally, no configuration file is used or required. If the file
\fB/etc/kopano/admin.cfg\fP exists, it is used. The following options can be
set in the configuration file:
.SS server_socket
.PP
URI for the connection to the Kopano server.
.PP
Default: (localhost connection via socket)
.SS sslkey_file
.PP
Use this file as key to logon to the server. This is only used when server_socket is set to
an HTTPS transport. See the kopano-server(8) manual page on how to setup SSL keys.
.SS sslkey_pass
.PP
The password of the SSL key file that is set in sslkey_file.
