.TH "KOPANO\-CACHESTAT" "8" "November 2016" "Kopano 8" "Kopano Core user reference"
.\" http://bugs.debian.org/507673
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kopano-cachestat \- Provides an easy\-to read overview of the kopano\-server cache statistics, as compared to the more low\-level "kopano\-stats \-\-system".
.SH "SYNOPSIS"
.HP \w'\fBkopano\-cachestat\fR\ 'u
\fBkopano\-cachestat\fR [\fIOPTION\fR...]
.SH "DESCRIPTION"
.PP
kopano\-cachestat displays the hit ratio and memory usage ratio of all caches on the kopano\-server. The cache sizes are configurable in kopano\-server\*(Aqs server.cfg.
.SH "OPTIONS"
.PP
\fB\-\-server\-socket\fR, \fB\-s\fR \fISOCKET\fR
.RS 4
Connect to kopano server through specified socket.
.RE
.PP
\fB\-\-ssl\-key\fR, \fB\-k\fR \fIFILE\fR
.RS 4
Specify SSL key file.
.RE
.PP
\fB\-\-ssl\-pass\fR, \fB\-p\fR \fIPASSWORD\fR
.RS 4
Specify SSL key password.
.RE
