'\" t
.\"     Title: kopano-monitor.cfg
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: November 2016
.\"    Manual: Kopano Core user reference
.\"    Source: Kopano 8
.\"  Language: English
.\"
.TH "KOPANO\-MONITOR.CFG" "5" "November 2016" "Kopano 8" "Kopano Core user reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kopano-monitor.cfg \- The Kopano monitor configuration file
.SH "SYNOPSIS"
.PP
\fBmonitor.cfg\fR
.SH "DESCRIPTION"
.PP
The
monitor.cfg
is a configuration file for the Kopano Monitor.
monitor.cfg
contains instructions for the software to set up the logging system.
.SH "FILE FORMAT"
.PP
The file consists of one big section, but parameters can be grouped by functionality.
.PP
The parameters are written in the form:
.PP
\fBname\fR
=
\fIvalue\fR
.PP
The file is line\-based. Each newline\-terminated line represents either a comment, nothing, a parameter or a directive. A line beginning with `#\*(Aq is considered a comment, and will be ignored by Kopano. Parameter names are case sensitive. Lines beginning with `!\*(Aq are directives.
.PP
Directives are written in the form:
.PP
!\fBdirective\fR
\fI[argument(s)] \fR
.PP
The following directives exist:
.PP
\fBinclude\fR
.RS 4
Include and process
\fIargument\fR
.PP
Example: !include common.cfg
.RE
.PP
The types of parameters for the spooler are: server, smtp and log.
.SH "EXPLANATION OF EACH PARAMETER"
.SS quota_check_interval
.PP
Set the interval (in minutes) for checking the quota for all Kopano users.
.PP
Default:
\fI15\fR
.SS mailquota_resend_interval
.PP
Send interval of a quota mail in days when a user reache his warning, soft or hard quota.
.PP
Default:
\fI1\fR
.SS server_socket
.PP
Connection URL to find the connection to the Kopano server.
.PP
Default:
\fIfile:///var/run/kopano/server.sock\fR
.SS run_as_user
.PP
After correctly starting, the monitor process will become this user, dropping root privileges. Note that the log file needs to be writeable by this user, and the directory too to create new logfiles after logrotation. This can also be achieved by setting the correct group and permissions.
.PP
Default: \fIkopano\fP
.SS run_as_group
.PP
After correctly starting, the monitor process will become this group, dropping root privileges.
.PP
Default: \fIkopano\fP
.SS pid_file
.PP
Write the process ID number to this file. This is used by the init.d script to correctly stop/restart the service.
.PP
Default value: /var/run/kopano/monitor.pid
.SS coredump_enabled
.PP
When a crash occurs or an assertion fails, a coredump file can be generated by
the system for use with a crash report. For details, see the
\fBkopano\-coredump\fP(5) manpage.
.PP
Default: \fIsystemdefault\fP
.SS sslkey_file
.PP
Use this file as key to logon to the server. This is only used when server_socket is set to an HTTPS transport. See the
\fBkopano-server\fR(8)
manual page on how to setup SSL keys.
.PP
Default: value not set.
.SS sslkey_pass
.PP
The password of the SSL key file that is set in sslkey_file.
.PP
Default: value not set.
.SS log_method
.PP
The method which should be used for logging. Valid values are:
.TP
\fBsyslog\fR
Use the syslog service. Messages will be sent using the "mail" facility tag. See also
\fBjournald.conf\fP(5) or \fBsyslog.conf\fP(5).
.TP
\fBfile\fP
Log to a file. The filename will be specified in
\fBlog_file\fR.
.TP
\fBauto\fP
Autoselect mode: If \fBlog_file\fP is set, that will be used.
Else, syslog will be used if it looks like it is available.
Else, stderr.
.PP
Default: \fIauto\fP
.SS log_file
.PP
When logging to a file, specify the filename in this parameter. Use
\fI\-\fR
(minus sign) for stderr output.
.PP
Default:
\fI\-\fP
.SS log_timestamp
.PP
Specify whether to prefix each log line with a timestamp in \*(Aqfile\*(Aq logging mode.
.PP
Default:
\fI1\fR
.SS log_buffer_size
.PP
Buffer logging in what sized blocks. The special value 0 selects line buffering.
.PP
Default:
\fI0\fR
.SS log_level
.PP
The level of output for logging in the range from 0 to 6. "0" means no logging,
"1" for critical messages only, "2" for error or worse, "3" for warning or
worse, "4" for notice or worse, "5" for info or worse, "6" debug.
.PP
Default:
\fI3\fP
.SS userquota_warning_template, companyquota_warning_template
.PP
These templates are read by the kopano\-monitor when a user or tenant exceeds a particular quota level. In these templates multiple variables can be used which will be replaced before sending the quota warning email.
.PP
These files should be saved in the UTF\-8 charset. UTF\-8 is compatible with US\-ASCII, so if you only use western characters, there is no need for special measurements.
.PP
\fI${KOPANO_QUOTA_NAME}\fR
.RS 4
userquota template: The name of the user who exceeded his quota
.PP
companyquota template: The name of the tenant which exceeded its quota
.RE
.PP
\fI${KOPANO_QUOTA_FULLNAME}\fR
.RS 4
userquota template: The fullname for the user who exceeded his quota
.PP
tenantquota template: The name of the tenant which exceeded its quota
.RE
.PP
\fI${KOPANO_QUOTA_COMPANY}\fR
.RS 4
userquota template: The name of the tenant to which the user belongs
.PP
tenantquota template: The name of the tenant which exceeded its quota
.RE
.PP
\fI${KOPANO_QUOTA_STORE_SIZE}\fR
.RS 4
userquota template: The total size of the user\*(Aqs store
.PP
companyquota template: The total size of all stores (including the public store) which belong to this tenant
.PP
Note: The size unit (KB,MB) is part of the variable
.RE
.PP
\fI${KOPANO_QUOTA_WARN_SIZE}\fR
.RS 4
The quota warning level
.PP
Note: The size unit (KB,MB) is part of the variable
.RE
.PP
\fI${KOPANO_QUOTA_SOFT_SIZE}\fR
.RS 4
The quota soft level
.PP
Note: The size unit (KB,MB) is part of the variable
.RE
.PP
\fI${KOPANO_QUOTA_HARD_SIZE}\fR
.RS 4
The quota hard limit
.PP
Note: The size unit (KB,MB) is part of the variable
.RE
.RE
.SH "RELOADING"
.PP
The following options are reloadable by sending the kopano\-monitor process a HUP signal:
.PP
log_level, mailquota_resend_interval
.SH "FILES"
.PP
/etc/kopano/monitor.cfg
.RS 4
The Kopano monitor configuration file.
.RE
.SH "AUTHOR"
.PP
Written by Kopano.
.SH "SEE ALSO"
.PP
\fBkopano-monitor\fR(8)
