.TH "KOPANO\-SPAMD" "8" "February 2018" "Kopano 8" "Kopano Core user reference"
.\" http://bugs.debian.org/507673
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kopano-spamd \- Kopano Spamd
.SH "SYNOPSIS"
.HP \w'\fBkopano\-spamd\fR\ 'u
\fBkopano\-spamd\fR
.SH "DESCRIPTION"
.PP
Spam learning daemon for Kopano / SpamAssasin.
Messages (if they do not have the X-Spam = YES flag) dragged into the Junk folder will be taught to SpamAssassin's sa-learn command.
Uses ICS for near realtime learning.
.SH "OPTIONS"
.PP
The Kopano spamd program takes the following configuration options:
.PP
\fB\-\-config\fR, \fB\-c\fR \fIfile\fR
.RS 4
Specify the location of the configuration file.
.sp
Default:
\fI/etc/kopano/spamd.cfg\fR
.RE
.PP
\fB\-\-server\-socket\fR, \fB\-s\fR \fIpath\fR
.RS 4
Connect to the storage server through
\fIpath\fR, e.g.
\fIfile:///path/to/socket\fP or \fIhttps://a.example:237/\fP.
.PP
Default: \fIfile:///var/run/kopano/server.sock\fP
.RE
.PP
When invoked with no options, the kopano\-spamd daemon will search for a configuration file in
/etc/kopano/search.cfg. If no configuration file is found, default values are used. See
\fBkopano-spamd.cfg\fR(5)
for all configuration options and their default values.
.SH "USAGE"
.PP
Starting the kopano\-spamd daemon with an alternative configuration:
.PP
\fBkopano\-spamd\fR\ 
\fB\-c\fR\ 
\fI/path/to/spamd.cfg\fR
.SH "SEE ALSO"
.PP
\fBkopano-server\fR(8),
\fBkopano-spamd.cfg\fR(5)
