.TH "KOPANO\-MR\-ACCEPT" "8" "November 2016" "Kopano 8" "Kopano Core user reference"
.\" http://bugs.debian.org/507673
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kopano-mr-accept \- Automatic accepting of meeting requests.
.SH "SYNOPSIS"
.HP \w'\fBkopano\-mr\-accept\fR\ 'u
\fBkopano\-mr\-accept\fR
.SH "DESCRIPTION"
.PP
Script will be called by
\fBkopano\-dagent\fR
when the user has enabled auto-accepting meeting requests using
\fBkopano\-admin\fR. It then automatically accepts all meeting requests and
removes decline meeting requests it receives. By default it always accepts all
meeting requests even when the invitee is busy, this can however be configured
with kopano-admin to decline on conflict or when recurring.
.PP
This script should not be executed from the command line.
.SH "SEE ALSO"
.PP
\fBkopano-dagent\fR(8)
\fBkopano-admin\fR(8)
