.TH "KOPANO\-AUTORESPOND" "8" "November 2016" "Kopano 8" "Kopano Core user reference"
.\" http://bugs.debian.org/507673
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kopano-autorespond \- Vacation message response script.
.SH "SYNOPSIS"
.HP \w'\fBkopano\-autorespond\fR\ 'u
\fBkopano\-autorespond\fR
.SH "DESCRIPTION"
.PP
Script will be called by
\fBkopano\-dagent\fR
when the user enabled a vacation message.
.PP
This script should not be executed from the command line.
.SH "SEE ALSO"
.PP
\fBkopano-dagent\fR(8)
