'\" t
.\"     Title: kopano-spooler.cfg
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: November 2016
.\"    Manual: Kopano Core user reference
.\"    Source: Kopano 8
.\"  Language: English
.\"
.TH "KOPANO\-SPOOLER.CFG" "5" "November 2016" "Kopano 8" "Kopano Core user reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kopano-spooler.cfg \- The Kopano spooler configuration file
.SH "SYNOPSIS"
.PP
\fBspooler.cfg\fR
.SH "DESCRIPTION"
.PP
The
spooler.cfg
is a configuration file for the Kopano Spooler.
spooler.cfg
contains instructions for the software to set up the logging system and outgoing smtp relay server.
.SH "FILE FORMAT"
.PP
The file consists of one big section, but parameters can be grouped by functionality.
.PP
The parameters are written in the form:
.PP
\fBname\fR
=
\fIvalue\fR
.PP
The file is line\-based. Each newline\-terminated line represents either a comment, nothing, a parameter or a directive. A line beginning with `#\*(Aq is considered a comment, and will be ignored by Kopano. Parameter names are case sensitive. Lines beginning with `!\*(Aq are directives.
.PP
Directives are written in the form:
.PP
!\fBdirective\fR
\fI[argument(s)] \fR
.PP
The following directives exist:
.PP
\fBinclude\fR
.RS 4
Include and process
\fIargument\fR
.PP
Example: !include common.cfg
.RE
.SH "EXPLANATION OF EACH PARAMETER"
.SS smtp_server
.PP
Hostname or IP address of the outgoing SMTP server. This server needs to relay mail for your server.
.PP
Default:
\fIlocalhost\fR
.SS smtp_port
.PP
TCP Port number for smtp_server.
.PP
Default:
\fI25\fR
.SS server_socket
.PP
Unix socket to find the connection to the Kopano server.
.PP
Default:
\fIfile:///var/run/kopano/server.sock\fR
.SS run_as_user
.PP
After correctly starting, the spooler process will become this user, dropping root privileges. Note that the log file needs to be writeable by this user, and the directory too to create new logfiles after logrotation. This can also be achieved by setting the correct group and permissions.
.PP
Default value is empty, not changing the user after starting.
.SS run_as_group
.PP
After correctly starting, the spooler process will become this group, dropping root privileges.
.PP
Default value is empty, not changing the group after starting.
.SS pid_file
.PP
Write the process ID number to this file. This is used by the init.d script to correctly stop/restart the service.
.PP
Default:
\fI/var/run/kopano/spooler.pid\fR
.SS running_path
.PP
Change directory to this path when running in daemonize mode. When using the \-F switch to run in the foreground the directory will not be changed.
.PP
Default:
\fI/\fR
.SS coredump_enabled
.PP
When a crash occurs or an assertion fails, a coredump file can be generated.
This file should be sent along with the crash report. It is turned on by
default in Kopano, but your system may have it disabled. For details, see the
\fBkopano\-coredump\fP(5) manpage.
.SS sslkey_file
.PP
Use this file as key to logon to the server. This is only used when server_socket is set to an HTTPS transport. See the
\fBkopano-server\fR(8)
manual page on how to setup SSL keys.
.PP
Default: value not set.
.SS sslkey_pass
.PP
The password of the SSL key file that is set in sslkey_file.
.PP
Default: value not set.
.SS log_method
.PP
The method which should be used for logging. Valid values are:
.TP
\fIsyslog\fR
Use the Linux system log. All messages will be written to the mail facility. See also
\fBsyslog.conf\fR(5).
.TP
\fIfile\fR
Log to a file. The filename will be specified in
\fBlog_file\fR.
.PP
Default:
\fIfile\fR
.SS log_file
.PP
When logging to a file, specify the filename in this parameter. Use
\fI\-\fR
(minus sign) for stderr output.
.PP
Default:
\fI\-\fP
.SS log_timestamp
.PP
Specify whether to prefix each log line with a timestamp in \*(Aqfile\*(Aq logging mode.
.PP
Default:
\fI1\fR
.SS log_buffer_size
.PP
Buffer logging in what sized blocks. The special value 0 selects line buffering.
.PP
Default:
\fI0\fR
.SS log_level
.PP
The level of output for logging in the range from 0 to 6. "0" means no logging,
"1" for critical messages only, "2" for error or worse, "3" for warning or
worse, "4" for notice or worse, "5" for info or worse, "6" debug.
.PP
Default:
\fI3\fP
.RE
.TP
\fBlog_raw_message_stage1\fP
Log the raw message to a file. In stage 1, not all recipients are necessarily
resolved yet, and Bcc is still visible; this is not the exact mail that is
delivered to the SMTP server. The file is saved to the location specified in
\fBlog_raw_message_path\fP. Default: \fBno\fP.
.TP
\fBlog_raw_message_path\fR
Path to save the raw message to. Default: \fB/tmp\fP.
.PP
\fBmax_threads\fR
.PP
The maximum number of threads used to send outgoing messages. For each email in the outgoing queue a separate thread will be started in order to allow multiple emails to be sent out simultaneously.
.PP
Default:
\fI5\fR
.SS fax_domain
.PP
When an email is sent to a contact with a FAX type email address, the address will be rewritten to a normal SMTP address, using the scheme: <faxnumber>@<fax_domain>. You can install software in your SMTP server which handles these email addresses to actually fax the message to that number.
.PP
Default:
.SS fax_international
.PP
When sending an international fax, the number will start with a \*(Aq+\*(Aq sign. You can rewrite this to the digits you need to dial when dialing to another country.
.PP
Default:
\fI+\fR
.SS always_send_delegates
.PP
Normally, a user needs to give explicit rights to other users to be able to send under their name. When setting this value to \*(Aqyes\*(Aq, the spooler will not check these permissions, and will always send the email with \*(AqOn behalf of\*(Aq headers. Please note that this feature overrides \*(Aqsend\-as\*(Aq functionality.
.PP
Default:
\fIno\fR
.SS always_send_tnef
.PP
Meeting requests will be sent using iCalendar files. This adds compatibility to more calendar programs. To use the previous TNEF (winmail.dat) method, set this option to \*(Aqyes\*(Aq.
.PP
When an email body is written in RTF text, normally this data is sent using TNEF. If you want to send an HTML representation of the email instead and not use TNEF, set this to \*(Aqminimal\*(Aq.
.PP
Default:
\fIno\fR
.SS enable_dsn
.PP
Enable the Delivery Status Notifications (DSN) for users. If a user requests a DSN the spooler sends the request to the MTA and when the MTA support this the user will receive the report in the mailbox. When the MTA doesn\*(Aqt support DSN the user will not receive a report. Ensure you have a supported MTA like postfix 2.3 and higher. If DSN is disabled and the user request a DSN then it will be ignored and the delivery report is not sent.
.PP
Default:
\fIyes\fR
.SS charset_upgrade
.PP
Upgrades the us\-ascii charset to this charset. This makes sure high\-characters in recipients and attachment filenames are correctly sent when the body is in plain text.
.PP
Default:
\fIwindows\-1252\fR
.SS allow_redirect_spoofing
.PP
Normally, users are not allowed to send e\-mail from a different e\-mail address than their own. However, the \*(Aqredirect\*(Aq rule sends e\-mails with their original \*(Aqfrom\*(Aq address. Enabling this option allows redirected e\-mails to be sent with their original \*(Aqfrom\*(Aq e\-mail address.
.PP
Default:
\fIyes\fR
.SS copy_delegate_mails
.PP
Make a copy of the sent mail of delegates in the sent items folder of the representee. This is done for both delegate and send\-as e\-mails.
.PP
Default:
\fIyes\fR
.SS allow_delegate_meeting_request
.PP
Normally, users are not allowed to send meeting requests as external delegate. However, when you want to forward meeting requests you need delegate permissions. Enabling this option allows you to sent and forward a meeting request as a delegate Kopano and SMTP user.
.PP
Default:
\fIyes\fR
.SS allow_send_to_everyone
.PP
When set to \*(Aqno\*(Aq, sending to the \*(Aqeveryone\*(Aq group is disallowed. The entire message will be bounced if this is attempted. When set to \*(Aqyes\*(Aq, this allows sending to all users in the \*(Aqeveryone\*(Aq group.
.PP
Default:
\fIyes\fR
.SS expand_groups
.PP
Expand groups in headers of sent e\-mails. This means that the recipient of an e\-mail with one or more groups as recipients will see the members of the groups instead of the groups themselves. If a group has an e\-mail address, the group is not expanded irrespective of this setting, since having an e\-mail address for the group implies that this address can be used to send messages to the group.
.PP
Default:
\fIno\fR
.SS archive_on_send
.PP
Archive outgoing messages. If an archive is attached to the mailbox from which a message is send, the message will immediately be archived to the special Outgoing folder.
.PP
Messages that are archived this way are not attached to the original message in the primary store. So there\*(Aqs no easy way to find the original sent item based on an archive or find an archive based on the sent item in the primary store. This option is only intended to make sure all outgoing messages are stored without the possibility for the owner to delete them.
.PP
Default:
\fIno\fR
.SS plugin_enabled
.PP
Enable or disable the spooler plugin framework.
.PP
Default:
\fIyes\fR
.SS plugin_manager_path
.PP
The path to the spooler plugin manager.
.PP
Default:
\fI/usr/share/kopano\-spooler/python\fR
.SS plugin_path
.PP
Path to the activated spooler plugins. This folder contains symlinks to the kopano plugins and custom scripts. The plugins are installed in
\fI/usr/share/kopano\-spooler/python/plugins\fR. To activate a plugin create a symbolic link in the
\fIplugin_path\fR
directory.
.PP
Example:
.PP
\fBln\fR
\fB\-s\fR
\fI/usr/share/kopano\-spooler/python/plugins/BMP2PNG.py\fR
\fI/var/lib/kopano/spooler/plugins/BMP2PNG.py\fR
.PP
Default:
\fI/var/lib/kopano/spooler/plugins\fR
.RE
.SH "RELOADING"
.PP
The following options are reloadable by sending the kopano\-spooler process a HUP signal:
.PP
log_level, max_threads, archive_on_send
.SH "FILES"
.PP
/etc/kopano/spooler.cfg
.RS 4
The Kopano spooler configuration file.
.RE
.SH "AUTHOR"
.PP
Written by Kopano.
.SH "SEE ALSO"
.PP
\fBkopano-spooler\fR(8)
