'\" t
.\"     Title: kopano-backup.cfg
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: November 2016
.\"    Manual: Kopano Core user reference
.\"    Source: Kopano 8
.\"  Language: English
.\"
.TH "KOPANO\-BACKUP.CFG" "5" "November 2016" "Kopano 8" "Kopano Core user reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kopano-backup.cfg \- The Kopano Backup configuration file
.SH "SYNOPSIS"
.PP
\fBbackup.cfg\fR
.SH "DESCRIPTION"
.PP
backup.cfg
is a configuration file for the Kopano Backup service.
.SH "FILE FORMAT"
.PP
The file consists of one big section, but parameters can be grouped by functionality.
.PP
The parameters are written in the form:
.PP
\fBname\fR
=
\fIvalue\fR
.PP
The file is line\-based. Each newline\-terminated line represents either a comment, nothing, a parameter or a directive. A line beginning with `#\*(Aq is considered a comment, and will be ignored by Kopano. Parameter names are case sensitive. Lines beginning with `!\*(Aq are directives.
.PP
Directives are written in the form:
.PP
!\fBdirective\fR
\fI[argument(s)] \fR
.PP
The following directives exist:
.PP
\fBinclude\fR
.RS 4
Include and process
\fIargument\fR
.sp
Example: !include common.cfg
.RE
.SH "EXPLANATION OF THE SERVER SETTINGS PARAMETERS"
.PP
\fBserver_socket\fR
.RS 4
Socket to find the connection to the Kopano server.
.sp
Default:
\fIfile:///var/run/kopano/server.sock\fR
.RE
.PP
\fBssl_key_file\fR
.RS 4
The file containing the private key and certificate. Please read the SSL section in the
\fBkopano-server\fR(8)
manual on how to create this file.
.sp
Default:
\fI/etc/kopano/ssl/search.pem\fR
.RE
.PP
\fBssl_key_pass\fR
.RS 4
Enter your password here when your key file contains a password to be readable.
.sp
No default set.
.RE
.SH "EXPLANATION OF THE LOG SETTINGS PARAMETERS"
.PP
\fBlog_method\fR
.RS 4
The method which should be used for logging. Valid values are:
.PP
\fIsyslog\fR
.RS 4
Use the Linux system log. All messages will be written to the mail facility. See also
\fBsyslog.conf\fR(5).
.RE
.PP
\fIfile\fR
.RS 4
Log to a file. The filename will be specified in
\fBlog_file\fR.
.RE
.sp
Default:
\fIfile\fR
.RE
.PP
\fBlog_level\fR
.RS 4
The level of output for logging in the range from 0 to 5. 0 means no logging, 5 means full logging.
.sp
Default:
\fI3\fR
.RE
.PP
\fBlog_file\fR
.RS 4
When logging to a file, specify the filename in this parameter. Use
\fI\-\fR
(minus sign) for stderr output.
.sp
Default:
\fI\-\fP
.RE
.SH "EXPLANATION OF THE BACKUP SETTINGS PARAMETERS"
.PP
\fBworker_processes\fR
.RS 4
Maximum number of stores to backup in parallel
.sp
Default: 1
.RE
.PP
\fBbackup_servers\fR
.RS 4
Only servers in this list will be processed by the backup tool. Servernames are SPACE seperated. Default is empty which will process all servers.
.sp
Default: value not set
.RE
.SH "AUTHOR"
.PP
Written by Kopano.
.SH "SEE ALSO"
.PP
\fBkopano-backup\fR(8)
