.TH "KOPANO\-SPAMD.CFG" "5" "February 2018" "Kopano 8" "Kopano Core user reference"
.\" http://bugs.debian.org/507673
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kopano-spamd.cfg \- The Kopano Spamd configuration file
.SH "SYNOPSIS"
.PP
\fBspamd.cfg\fR
.SH "DESCRIPTION"
.PP
The
spamd.cfg
is a configuration file for the Kopano Spamd Service.
spamd.cfg
contains instructions for the software to set up the connection, indexing and logging systems.
.SH "FILE FORMAT"
.PP
The file consists of one big section, but parameters can be grouped by functionality.
.PP
The parameters are written in the form:
.PP
\fBname\fR
=
\fIvalue\fR
.PP
The file is line\-based. Each newline\-terminated line represents either a comment, nothing, a parameter or a directive. A line beginning with \fB#\fP is considered a comment, and will be ignored by Kopano. Parameter names are case sensitive. Lines beginning with \fB!\fP are directives.
.PP
Directives are written in the form:
.PP
!\fBdirective\fR
\fI[argument(s)] \fR
.PP
The following directives exist:
.PP
\fBinclude\fR
.RS 4
Include and process
\fIargument\fR
.sp
Example: !include common.cfg
.RE
.SH "EXPLANATION OF THE SERVICE SETTINGS PARAMETERS"
.SS run_as_user
.PP
During startup, the process will switch to run using this user identity. Note
that the log file and directory need to be writeable by this user (this is
normally the case when using packages).
.PP
Default: \fIkopano\fP
.SS run_as_group
.PP
During startup, the process will switch to run using this user identity.
.PP
Default: \fIkopano\fP
.SS pid_file
.PP
Write the process ID number to this file. This can be used by sysvinit scripts.
.PP
Default:
\fI/var/run/kopano/spamd.pid\fR
.SH "EXPLANATION OF THE SERVER SETTINGS PARAMETERS"
.SS server_socket
.PP
Socket to find the connection to the Kopano server.
.PP
Default:
\fIfile:///var/run/kopano/server.sock\fR
.SS sslkey_file
.PP
The file containing the private key and certificate. Please read the SSL section in the
\fBkopano-server\fR(8)
manual on how to create this file.
.PP
Default:
\fI/etc/kopano/ssl/spamd.pem\fR
.SS sslkey_pass
.PP
Enter your password here when your key file contains a password to be readable.
.PP
No default set.
.SH "EXPLANATION OF THE LOG SETTINGS PARAMETERS"
.SS log_method
.PP
The method which should be used for logging. Valid values are:
.TP
\fBsyslog\fP
Use the Linux system log. All messages will be written to the mail facility. See also \fBsyslog.conf\fR(5).
.TP
\fBfile\fP
Log to a file. The filename will be specified in \fBlog_file\fR.
.PP
Default:
\fIfile\fR
.SS log_level
.PP
The level of output for logging in the range from 0 to 5. 0 means no logging, 5 means full logging.
.PP
Default:
\fI3\fR
.SS log_file
.PP
When logging to a file, specify the filename in this parameter. Use
\fB\-\fP
(minus sign) for stderr output.
.PP
Default:
\fI/var/log/kopano/spamd.log\fR
.SS log_timestamp
.PP
Specify whether to prefix each log line with a timestamp in "file" logging mode.
.PP
Default:
\fI1\fR
.SS log_buffer_size
.PP
Buffer logging in what sized blocks. The special value 0 selects line buffering.
.PP
Default:
\fI0\fR
.SH "EXPLANATION OF THE ADVANCED SETTINGS PARAMETERS"
.SS spam_dir
.PP
The dir where spam mails are written to which are later picked up by the sa-learn program.
.PP
Default: \fI/var/lib/kopano/spamd/spam\fR
.SS spam_db
.PP
Location for the database containing metadata on learned spam.
.PP
Default: \fI/var/lib/kopano/spamd/spam.db\fR
.SS header_tag
.PP
Header tag for spam message. X-Spam-Flag, X-Spam-Status, X-Spam
.PP
Default: \fIX-Spam-Flag\fR
.SS learn_ham
.PP
Learn ham, when the user moves emails from junk to inbox, enabled by default.
.PP
Default: \fIyes\fR
.SS ham_dir
.PP
The dir where ham mails are written to which are later picked up by the sa-learn program
.PP
Default: \fI/var/lib/kopano/spamd/ham\fR
.SS sa_group
.PP
Spamassassin group
.PP
Default: \fIamavis\fR
.SH "SEE ALSO"
.PP
\fBkopano-spamd\fR(8)
