.TH "KOPANO\-SEARCH.CFG" "5" "November 2016" "Kopano 8" "Kopano Core user reference"
.\" http://bugs.debian.org/507673
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kopano-search.cfg \- The Kopano Search configuration file
.SH "SYNOPSIS"
.PP
\fBsearch.cfg\fR
.SH "DESCRIPTION"
.PP
The
search.cfg
is a configuration file for the Kopano Search Service.
search.cfg
contains instructions for the software to set up the connection, indexing and logging systems.
.SH "FILE FORMAT"
.PP
The file consists of one big section, but parameters can be grouped by functionality.
.PP
The parameters are written in the form:
.PP
\fBname\fR
=
\fIvalue\fR
.PP
The file is line\-based. Each newline\-terminated line represents either a comment, nothing, a parameter or a directive. A line beginning with \fB#\fP is considered a comment, and will be ignored by Kopano. Parameter names are case sensitive. Lines beginning with \fB#\fP are directives.
.PP
Directives are written in the form:
.PP
!\fBdirective\fR
\fI[argument(s)] \fR
.PP
The following directives exist:
.PP
\fBinclude\fR
.RS 4
Include and process
\fIargument\fR
.sp
Example: !include common.cfg
.RE
.SH "EXPLANATION OF THE SERVICE SETTINGS PARAMETERS"
.SS index_path
.PP
Directory under which all index files will be placed.
.PP
Default:
\fI/var/lib/kopano/index/\fR
.SS run_as_user
.PP
During startup, the process will switch to run using this user identity. Note
that the log file and directory need to be writeable by this user (this is
normally the case when using packages).
.PP
Default: \fIkopano\fP
.SS run_as_group
.PP
During startup, the process will switch to run using this user identity.
.PP
Default: \fIkopano\fP
.SS pid_file
.PP
Write the process ID number to this file. This can be used by sysvinit scripts.
.PP
Default:
\fI/var/run/kopano/search.pid\fR
.SS limit_results
.PP
Limit the number of results returned to the server. If set to a nonzero value, only the N most relevant results will be returned to the server. This in turn limits the number of results that the user will see. If the limit is set to 0, all results will be returned.
.PP
Default:\fI1000\fR
.SH "EXPLANATION OF THE SERVER SETTINGS PARAMETERS"
.SS server_socket
.PP
Socket to find the connection to the Kopano server.
.PP
Default:
\fIfile:///var/run/kopano/server.sock\fR
.SS sslkey_file
.PP
The file containing the private key and certificate. Please read the SSL section in the
\fBkopano-server\fR(8)
manual on how to create this file.
.PP
Default:
\fI/etc/kopano/ssl/search.pem\fR
.SS sslkey_pass
.PP
Enter your password here when your key file contains a password to be readable.
.PP
No default set.
.SH "EXPLANATION OF THE LISTEN SETTINGS PARAMETERS"
.SS server_bind_name
.PP
Connection path to which other processes can connect with the kopano\-search for performing search queries.
.PP
Use
\fIhttp://0.0.0.0:port\fR
to listen as an HTTP service on all IPv4 interfaces on the given
\fIport\fR
number.
.PP
Default:
\fIfile:///var/run/kopano/search.sock\fR
.SS ssl_private_key_file
.PP
kopano\-search will use this file as private key for SSL TLS. This file can be created with:
\fBopenssl genrsa \-out /etc/kopano/search/privkey.pem 2048\fR.
.PP
Default:
\fI/etc/kopano/search/privkey.pem\fR
.SS ssl_certificate_file
.PP
kopano\-search will use this file as certificate for SSL TLS. A self\-signed certificate can be created with:
\fBopenssl req \-new \-x509 \-key /etc/kopano/search/privkey.pem \-out /etc/kopano/search/cert.pem \-days 1095\fR.
.PP
Default:
\fI/etc/kopano/search/cert.pem\fR
.SH "EXPLANATION OF THE LOG SETTINGS PARAMETERS"
.SS log_method
.PP
The method which should be used for logging. Valid values are:
.TP
\fBsyslog\fP
Use the Linux system log. All messages will be written to the mail facility. See also \fBsyslog.conf\fR(5).
.TP
\fBfile\fP
Log to a file. The filename will be specified in \fBlog_file\fR.
.PP
Default:
\fIfile\fR
.SS log_level
.PP
The level of output for logging in the range from 0 to 6. 0 means no logging, 6 means debug logging.
.PP
Default:
\fI3\fR
.SS log_file
.PP
When logging to a file, specify the filename in this parameter. Use
\fB\-\fP
(minus sign) for stderr output.
.PP
Default:
\fI\-\fP
.SS log_timestamp
.PP
Specify whether to prefix each log line with a timestamp in "file" logging mode.
.PP
Default:
\fI1\fR
.SS log_buffer_size
.PP
Buffer logging in what sized blocks. The special value 0 selects line buffering.
.PP
Default:
\fI0\fR
.SH "EXPLANATION OF THE ADVANCED SETTINGS PARAMETERS"
.SS search_engine
.PP
Backend search engine (currently only xapian is supported).
.PP
Default: \fIxapian\fP
.PP
The size in bytes of the term cache used when writing terms to the index. A larger term cache will increase indexing speed when indexing large number of documents in a single store. This will barely affect incremental updates after the initial indexing has finished. This value may contain a k, m or g multiplier.
.PP
Default: \fI64M\fP
.SS index_exclude_properties
.PP
Some properties are ignored because they contain unrelated information for users to find their messages on. A default set of ignored property ids is set here, but can be expanded. Only the id part of a property is needed, and must be string typed properties. The field is space separated.
.PP
Default: \fI007D 0064 0C1E 0075 678E 678F\fP
.SS index_processes
.PP
Number of indexing processes used during initial indexing. Setting this to a higher value can greatly speed up initial indexing, especially when attachments are indexed.
.PP
Default: \fI1\fP
.SS index_drafts
.PP
Index drafts folders
.PP
Default: \fIyes\fP
.SS index_junk
.PP
Index junk folders
.PP
Default: \fIyes\fP
.SS suggestions
.PP
Prepare search suggestions ("did\-you\-mean?") during indexing. Junk folders are excluded. This takes up a large percentage of the used disk space.
.PP
Default: \fIyes\fP
.SH "EXPLANATION OF THE ATTACHMENT SETTINGS PARAMETERS"
.SS index_attachments
.PP
Enable indexing of attachments. When attachments are being indexed, searching for keywords in the body of a message will automatically cause the attachment to be searched as well.
.PP
This will slow down the indexing process, require more system memory and increases index file size.
.PP
Default:
\fIno\fR
.SS index_attachment_max_size
.PP
Maxiumum file size for attachments to be indexed. Any attachment larger then this amount will not be indexed. This value may contain a k, m or g multiplier.
.PP
Default:
\fI5M\fR
.SH "SEE ALSO"
.PP
\fBkopano-search\fR(8)
