.TH kopano\-statsd 8 "2018-10-05" "Kopano 8" "Kopano Groupware Core reference"
.SH Name
kopano\-statsd \(em statistics collection daemon
.SH Synopsis
\fBkopano\-statsd\fP [\fB\-c\fP \fIconfigfile\fP]
.SH Description
.PP
This service receives statistics submissions from kopano-dagent, kopano-spooler
and kopano-server and stores them in a round-robin database from which graphs
can be created at a later time with rrdgraph(1).
.PP
PNG image creation is not part of kopano-statsd. This is presently left in the
hands of the administrator, because styling is a user preference, and because
some environments may want to use an on-demand _or_ a gratitious periodic image
generation, depending on the system's purpose and expected performance
characteristics.
.SH Options
.TP
\fB\-c\fP \fIconfigfile\fP
Load an alternate config file. If none is specified, statsd.cfg will be sourced
if available.
.SH Configuration file
.PP
The format of the configuration file follows the same key=value scheme from
other Kopano config files.
.SH See also
.PP
\fBkopano\-statsd.cfg\fP(5)
