'\" t
.\"     Title: kopano-monitor.cfg
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: November 2016
.\"    Manual: Kopano Core user reference
.\"    Source: Kopano 8
.\"  Language: English
.\"
.TH "KOPANO\-MONITOR.CFG" "5" "November 2016" "Kopano 8" "Kopano Core user reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kopano-monitor.cfg \- The Kopano monitor configuration file
.SH "SYNOPSIS"
.PP
\fBmonitor.cfg\fR
.SH "DESCRIPTION"
.PP
The
monitor.cfg
is a configuration file for the Kopano Monitor.
monitor.cfg
contains instructions for the software to set up the logging system.
.SH "FILE FORMAT"
.PP
The file consists of one big section, but parameters can be grouped by functionality.
.PP
The parameters are written in the form:
.PP
\fBname\fR
=
\fIvalue\fR
.PP
The file is line\-based. Each newline\-terminated line represents either a comment, nothing, a parameter or a directive. A line beginning with `#\*(Aq is considered a comment, and will be ignored by Kopano. Parameter names are case sensitive. Lines beginning with `!\*(Aq are directives.
.PP
Directives are written in the form:
.PP
!\fBdirective\fR
\fI[argument(s)] \fR
.PP
The following directives exist:
.PP
\fBinclude\fR
.RS 4
Include and process
\fIargument\fR
.sp
Example: !include common.cfg
.RE
.PP
The types of parameters for the spooler are: server, smtp and log.
.SH "EXPLANATION OF EACH PARAMETER"
.PP
\fBquota_check_interval\fR
.RS 4
Set the interval (in minutes) for checking the quota for all Kopano users.
.sp
Default:
\fI15\fR
.RE
.PP
\fBmailquota_resend_interval\fR
.RS 4
Send interval of a quota mail in days when a user reache his warning, soft or hard quota.
.sp
Default:
\fI1\fR
.RE
.PP
\fBserver_socket\fR
.RS 4
Connection URL to find the connection to the Kopano server.
.sp
Default:
\fIfile:///var/run/kopano/server.sock\fR
.RE
.PP
\fBrun_as_user\fR
.RS 4
After correctly starting, the monitor process will become this user, dropping root privileges. Note that the log file needs to be writeable by this user, and the directory too to create new logfiles after logrotation. This can also be achieved by setting the correct group and permissions.
.sp
Default value is empty, not changing the user after starting.
.RE
.PP
\fBrun_as_group\fR
.RS 4
After correctly starting, the monitor process will become this group, dropping root privileges.
.sp
Default value is empty, not changing the group after starting.
.RE
.PP
\fBpid_file\fR
.RS 4
Write the process ID number to this file. This is used by the init.d script to correctly stop/restart the service.
.sp
Default value: /var/run/kopano/monitor.pid
.RE
.PP
\fBrunning_path\fR
.RS 4
Change directory to this path when running in daemonize mode. When using the \-F switch to run in the foreground the directory will not be changed.
.sp
Default:
\fI/\fR
.RE
.PP
\fBsslkey_file\fR
.RS 4
Use this file as key to logon to the server. This is only used when server_socket is set to an HTTPS transport. See the
\fBkopano-server\fR(8)
manual page on how to setup SSL keys.
.sp
Default: value not set.
.RE
.PP
\fBsslkey_pass\fR
.RS 4
The password of the SSL key file that is set in sslkey_file.
.sp
Default: value not set.
.RE
.PP
\fBlog_method\fR
.RS 4
The method which should be used for logging. Valid values are:
.PP
\fIsyslog\fR
.RS 4
Use the Linux system log. All messages will be written to the mail facility. See also
\fBsyslog.conf\fR(5).
.RE
.PP
\fIfile\fR
.RS 4
Log to a file. The filename will be specified in
\fBlog_file\fR.
.RE
.sp
Default:
\fIfile\fR
.RE
.PP
\fBlog_file\fR
.RS 4
When logging to a file, specify the filename in this parameter. Use
\fI\-\fR
(minus sign) for stderr output.
.sp
Default:
\fI/var/log/kopano/monitor.log\fR
.RE
.PP
\fBlog_timestamp\fR
.RS 4
Specify whether to prefix each log line with a timestamp in \*(Aqfile\*(Aq logging mode.
.sp
Default:
\fI1\fR
.RE
.PP
\fBlog_buffer_size\fR
.RS 4
Buffer logging in what sized blocks. The special value 0 selects line buffering.
.sp
Default:
\fI0\fR
.RE
.PP
\fBlog_level\fR
.RS 4
The level of output for logging in the range from 0 to 5. 0 means no logging, 5 means full logging.
.sp
Default:
\fI2\fR
.RE
.PP
\fBuserquota_warning_template\fR, \fBcompanyquota_warning_template\fR
.RS 4
These templates are read by the kopano\-monitor when a user or tenant exceeds a particular quota level. In these templates multiple variables can be used which will be replaced before sending the quota warning email.
.sp
These files should be saved in the UTF\-8 charset. UTF\-8 is compatible with US\-ASCII, so if you only use western characters, there is no need for special measurements.
.PP
\fI${KOPANO_QUOTA_NAME}\fR
.RS 4
userquota template: The name of the user who exceeded his quota
.sp
companyquota template: The name of the tenant which exceeded its quota
.RE
.PP
\fI${KOPANO_QUOTA_FULLNAME}\fR
.RS 4
userquota template: The fullname for the user who exceeded his quota
.sp
tenantquota template: The name of the tenant which exceeded its quota
.RE
.PP
\fI${KOPANO_QUOTA_COMPANY}\fR
.RS 4
userquota template: The name of the tenant to which the user belongs
.sp
tenantquota template: The name of the tenant which exceeded its quota
.RE
.PP
\fI${KOPANO_QUOTA_STORE_SIZE}\fR
.RS 4
userquota template: The total size of the user\*(Aqs store
.sp
companyquota template: The total size of all stores (including the public store) which belong to this tenant
.sp
Note: The size unit (KB,MB) is part of the variable
.RE
.PP
\fI${KOPANO_QUOTA_WARN_SIZE}\fR
.RS 4
The quota warning level
.sp
Note: The size unit (KB,MB) is part of the variable
.RE
.PP
\fI${KOPANO_QUOTA_SOFT_SIZE}\fR
.RS 4
The quota soft level
.sp
Note: The size unit (KB,MB) is part of the variable
.RE
.PP
\fI${KOPANO_QUOTA_HARD_SIZE}\fR
.RS 4
The quota hard limit
.sp
Note: The size unit (KB,MB) is part of the variable
.RE
.RE
.SH "RELOADING"
.PP
The following options are reloadable by sending the kopano\-monitor process a HUP signal:
.PP
log_level, mailquota_resend_interval, userquota_warning_template
.RS 4
.RE
.SH "FILES"
.PP
/etc/kopano/monitor.cfg
.RS 4
The Kopano monitor configuration file.
.RE
.SH "AUTHOR"
.PP
Written by Kopano.
.SH "SEE ALSO"
.PP
\fBkopano-monitor\fR(8)
