'\" t
.\"     Title: kopano-cli
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: June 2017
.\"    Manual: Kopano Core user reference
.\"    Source: Kopano 8
.\"  Language: English
.\"
.TH "KOPANO\-CLI" "8" "June 2017" "Kopano 8" "Kopano Core user reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kopano-cli \- The Kopano Command-line Interface
.SH "SYNOPSIS"
.HP \w'\fBkopano\-cli\fR\ 'u
\fBkopano\-cli\fR [\fIOPTION\fR...]
.SH "DESCRIPTION"
.PP
Kopano\-cli is used to manage a Kopano server (cluster), including users, stores, groups and companies. This includes listing/creation/deletion of objects, and changing settings such as quota limits, delegation, out-of-office settings and store and folder-level permissions.
.PP
.SH "OPTIONS"
.PP
\fB\-\-active\fR \fI{\fByes\fR|\fBno\fR}\fR
.RS 4
Change or specify if user is active. Should be combined with --user (and optionally --create).
.RE
.PP
\fB\-\-add-admin\fR \fINAME\fR
.RS 4
Add specified user as "remote-admin" for company specified with --company.
.RE
.PP
\fB\-\-add-company-quota-recipient\fR \fINAME\fR
.RS 4
Add specified user to companyquota recipients for company specified with --company.
.RE
.PP
\fB\-\-add-delegation\fR \fINAME\fR
.RS 4
Add specified delegation (flags) to user specified with --user. The syntax to be used for delegation (flags) is 'user:flag1,flag2,..' where 'user' is a user name, and flags are optionally chosen from the following: see_private, send_copy. The first means that delegates can see private items, and the second that meeting requests and responses are also sent to the delegates.
.RE
.PP
\fB\-\-add-feature\fR \fINAME\fR
.RS 4
Enable specified feature for user specified with --user.
.RE
.PP
\fB\-\-add-permission\fR \fINAME\fR
.RS 4
Add specified permissions to store of user specified with --user. Can be used with --folder to add permissions for a specific folder. The syntax to be used for permissions is 'member:right1,right..', where 'member' is a group or user name, and rights are chosen from the following: read_items, create_items, create_subfolders, edit_own, edit_all, delete_own, delete_all, folder_owner, folder_contact and folder_visible. So for example, to add certain permissions to the inbox of a user 'user2', to the inbox of user 'user1': --user user1 --folder Inbox --add-permission user2:read_items,folder_visible. The colon is optional.
.RE
.PP
\fB\-\-add-sendas\fR \fINAME\fR
.RS 4
Allow specified user to "send as" user specified with --user.
.RE
.PP
\fB\-\-add-userquota-recipient\fR \fINAME\fR
.RS 4
Add specified user to userquota recipients for company specified with --company.
.RE
.PP
\fB\-\-add-view\fR \fINAME\fR
.RS 4
Add specified company as remote-viewer of address book.
.RE
.PP
\fB\-\-add-user\fR \fINAME\fR
.RS 4
Add specified user to group specified with --group.
.RE
.PP
\fB\-\-admin\fR \fINAME\fR
.RS 4
Make specified user administrator of company specified with --company.
.RE
.PP
\fB\-\-admin-level\fR \fIN\fR
.RS 4
Change or specify admin level for user specified with --user. A value of 1 means the user is an administrator, and 2 means the user is a system administrator.
.RE
.PP
\fB\-\-clear-cache\fR
.RS 4
Clear all server caches.
.RE
.PP
\fB\-\-company\fR, \fB\-C\fR \fINAME\fR
.RS 4
Specify company. Without further arguments, this will show information about the given company. Can also be used in combination with e.g. --list-users.
.RE
.PP
\fB\-\-config\fR, \fB\-c\fR \fIFILE\fR
.RS 4
Load configuration settings from specified file.
.RE
.PP
\fB\-\-create\fR
.RS 4
Create object. Must be combined with --user, --group or --company. Can be combined with options such as --fullname, --email and --password. Note that this doesn't work with an external source such as LDAP.
.RE
.PP
\fB\-\-create-store\fR
.RS 4
Create and hook store. Without further arguments, a public store is created for the current company or server. Can be used in combination with --company (to create a company public store) and --user (tot create a user store).
.RE
.PP
\fB\-\-debug\fR
.RS 4
Enable debug mode, meaning full tracebacks are shown in addition to error messages.
.RE
.PP
\fB\-\-delete\fR
.RS 4
Delete object. Must be combined with --user, --group or --company. Note that this doesn't work with an external source such as LDAP.
.RE
.PP
\fB\-\-email\fR \fINAME\fR
.RS 4
Change or specify object email address. Can be used with --user or --group (and optionally --create).
.RE
.PP
\fB\-\-folder\fR, \fB\-f\fR \fIPATH\fR
.RS 4
Specify folder. Can be used in combination with e.g. --add-permission, to add permissions for a specific folder.
\fI\-\-recursive\fR.
.RE
.PP
\fB\-\-fullname\fR \fINAME\fR
.RS 4
Change or specify object full name. Can be used with --user, --group or --company (and optionally --create).
.RE
.PP
\fB\-\-group\fR, \fB\-G\fR \fINAME\fR
.RS 4
Specify group. Without further arguments, this will show information about the given group. Can also be used in combination with e.g. --list-users.
.RE
.PP
\fB\-\-hook-store\fR \fIGUID\fR
.RS 4
Hook store with specified GUID. Without further arguments, this will hook the public store. Can be used in combination with --company (to hook the public store) and --user (to hook the user store).
.RE
.PP
\fB\-\-hook-archive\fR \fIGUID\fR
.RS 4
Hook archive store with specified GUID. Should be used in combination with --user.
.RE
.PP
\fB\-\-lang\fR \fILANG\fR
.RS 4
Specify language in which new stores are created, determining e.g. the name of the inbox.
.RE
.PP
\fB\-\-mr-accept\fR \fI{\fByes\fR|\fBno\fR}\fR
.RS 4
Change or specify if meeting requests are automatically accepted (by script specified in dagent.cfg). Should be combined with --user.
.RE
.PP
\fB\-\-mr-accept-conflicts\fR \fI{\fByes\fR|\fBno\fR}\fR
.RS 4
Change or specify if overlapping meeting requests are automatically declined by accept script. Should be combined with --user.
.RE
.PP
\fB\-\-mr-accept-recurring\fR \fI{\fByes\fR|\fBno\fR}\fR
.RS 4
Change or specify if recurring meeting requests are automatically declined by accept script. Should be combined with --user.
.RE
.PP
\fB\-\-list-users\fR
.RS 4
List users. Without further arguments, this will list all users. Can also be used in combination with e.g. --company and --group.
.RE
.PP
\fB\-\-list-groups\fR
.RS 4
List groups. Without further arguments, this will list all groups. Can also be used in combination with e.g. --company.
.RE
.PP
\fB\-\-list-companies\fR
.RS 4
List companies.
.RE
.PP
\fB\-\-list-orphans\fR
.RS 4
List orphans, meaning stores that are currently not hooked to a user or public store.
.RE
.PP
\fB\-\-name\fR \fINAME\fR
.RS 4
Change or specify object name. Can be used with --user, --group or --company (and optionally --create).
.RE
.PP
\fB\-\-ooo\fR \fI{\fByes\fR|\fBno\fR}\fR
.RS 4
Enable or disable out-of-office replies for user specified with --user.
.RE
.PP
\fB\-\-ooo-clear\fR
.RS 4
Clear out-of-office settings for user specified with --user.
.RE
.PP
\fB\-\-ooo-subject\fR \fINAME\fR
.RS 4
Change or specify out-of-office subject for user specified with --user.
.RE
.PP
\fB\-\-ooo-message\fR \fIPATH\fR
.RS 4
Change or specify out-of-office message for user specified with --user, by specifying a file containing the message.
.RE
.PP
\fB\-\-ooo-from\fR \fINAME\fR
.RS 4
Change or specify out-of-office from date for user specified with --user.
.RE
.PP
\fB\-\-ooo-until\fR \fINAME\fR
.RS 4
Change or specify out-of-office until date for user specified with --user.
.RE
.PP
\fB\-\-password\fR \fINAME\fR
.RS 4
Change or specify user password. Should be used in combination with --user (and optionally --create).
.RE
.PP
\fB\-\-password\-prompt\fR
.RS 4
Change or specify user password via prompt. Should be used in combination with --user (and optionally --create).
.RE
.PP
\fB\-\-purge-softdelete\fR \fIN\fR
.RS 4
Purge items marked as softdeleted more than N days ago.
.RE
.PP
\fB\-\-purge-deferred\fR
.RS 4
Purge all items in the deferred update table.
.RE
.PP
\fB\-\-quota-override\fR \fI{\fByes\fR|\fBno\fR}\fR
.RS 4
Override server quota limits for user specified with --user or company specified with --company.
.RE
.PP
\fB\-\-quota-hard\fR \fIN\fR
.RS 4
Change or specify hard quota limit at specified number of megabytes (MB). Should be used with --user or --company.
.RE
.PP
\fB\-\-quota-soft\fR \fIN\fR
.RS 4
Change or specify soft quota limit at specified number of megabytes (MB). Should be used with --user or --company.
.RE
.PP
\fB\-\-quota-warn\fR \fIN\fR
.RS 4
Change or specify warn quota limit at specified number of megabytes (MB). Should be used with --user or --company.
.RE
.PP
\fB\-\-remove-store\fR \fIGUID\fR
.RS 4
Remove orphaned store with specified GUID.
.RE
.PP
\fB\-\-remove-admin\fR \fINAME\fR
.RS 4
Remove specified user as "remote-admin" for company specified with --company.
.RE
.PP
\fB\-\-remove-company-quota-recipient\fR \fINAME\fR
.RS 4
Remove specified user from companyquota recipients for company specified with --company.
.RE
.PP
\fB\-\-remove-delegation\fR \fINAME\fR
.RS 4
Remove delegation (flags) for user specified with --user. The syntax to be used is described for the --add-delegation option.
.RE
.PP
\fB\-\-remove-feature\fR \fINAME\fR
.RS 4
Disable specified feature for user specified with --user.
.RE
.PP
\fB\-\-remove-permission\fR \fINAME\fR
.RS 4
Remove specified permissions to store of user specified with --user. Can be used with --folder to remove permissions for a specific folder. The syntax to be used for permissions is described for the --add-permission option.
.RE
.PP
\fB\-\-remove-sendas\fR \fINAME\fR
.RS 4
Disallow specified user to "send as" user specified with --user.
.RE
.PP
\fB\-\-remove-userquota-recipient\fR \fINAME\fR
.RS 4
Remove specified user from userquota recipients for company specified with --company.
.RE
.PP
\fB\-\-remove-view\fR \fINAME\fR
.RS 4
Remove specified company as remote-viewer of address book.
.RE
.PP
\fB\-\-remove-user\fR \fINAME\fR
.RS 4
Remove specified user from group specified with --group.
.RE
.PP
\fB\-\-reset-folder-count\fR
.RS 4
Reset folder counts for all folders of user given with --user.
.RE
.PP
\fB\-\-send-only-to-delegates\fR \fI{\fByes\fR|\fBno\fR}\fR
.RS 4
When sending meeting requests and responses to delegates, only send them to the delegates.
.RE
.PP
\fB\-\-server\-socket\fR, \fB\-s\fR \fISOCKET\fR
.RS 4
Connect to storage server through specified socket.
.RE
.PP
\fB\-\-ssl\-key\fR, \fB\-k\fR \fIFILE\fR
.RS 4
Specify SSL key file.
.RE
.PP
\fB\-\-ssl\-pass\fR, \fB\-p\fR \fIPASSWORD\fR
.RS 4
Specify SSL key password.
.RE
.PP
\fB\-\-sync\fR
.RS 4
Synchronize users, groups and companies with external source (such as LDAP).
.RE
.PP
\fB\-\-unhook-archive\fR
.RS 4
Unhook archive store. Should be combined with --user.
.RE
.PP
\fB\-\-unhook-store\fR
.RS 4
Unhook store. Without further arguments, the public store is unhooked. Can be used in combination with --company (to unhook the public store) or --user (to unhook the user store).
.RE
.PP
\fB\-\-user\fR, \fB\-u\fR \fINAME\fR
.RS 4
Specify user. Without further arguments, this will show information about the given user.
.RE
.PP
\fB\-\-user-count\fR
.RS 4
Output user statistics, such as active and non-active users and total user count.
.RE
.SH "EXAMPLES"
.PP
To create a new user:
.PP
\fBkopano\-cli \-\-create \-u john \-\-fullname "john doe" \-\-password john \-\-email john@doe.com\fR
.PP
To modify the password and e-mail address:
.PP
\fBkopano\-cli \-u john \-\-password john \-\-email john@doe.com\fR
.PP
To set out of office for a user:
.PP
\fBkopano\-cli \-u john \-\-ooo-active yes \-\-ooo-subject "On vacation" \-\-ooo-message /etc/kopano/ooo/vacation.html\fR
.PP
To delete a user:
.PP
\fBkopano\-cli \-\-delete \-u john\fR
.PP
To set permission on a calendar folder:
.PP
\fBkopano\-cli \-u john \-\-folder Calendar \-\-add\-permission everyone:read_items,folder_visible\fR
.PP
To set permission on a store:
.PP
\fBkopano\-cli \-u john \-\-add\-permission joe:read_items,folder_visible\fR
.SH "AUTHOR"
.PP
Written by Kopano.
