'\" t
.\"     Title: kopano-spooler
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: November 2016
.\"    Manual: Kopano Core user reference
.\"    Source: Kopano 8
.\"  Language: English
.\"
.TH "KOPANO\-SPOOLER" "8" "November 2016" "Kopano 8" "Kopano Core user reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kopano-spooler \- Start the Kopano spooler.
.SH "SYNOPSIS"
.HP \w'\fBkopano\-spooler\fR\ 'u
\fBkopano\-spooler\fR [\fIOPTION\fR...] [\fISERVERNAME\fR]
.SH "DESCRIPTION"
.PP
The spooler sends all pending Kopano e\-mail to the recipients. When started, the program will keep running and sending messages whenever needed.
.PP
The outgoing mailserver can be overwritten from the config file by specifying this on the commandline.
.PP
The default settings of the spooler program are defined in
\fBkopano-spooler.cfg\fR(5).
.SH "OPTIONS"
.PP
Various options are possible. None of these options are required.
.PP
\fB\-\-config\fR, \fB\-c\fR \fIspooler.cfg\fR
.RS 4
Specify the location of the spooler.cfg file. If the spooler.cfg file is not specified, the spooler will try to load
/etc/kopano/spooler.cfg. If that file is not present, it will continue using its default settings.
.RE
.PP
\fB\-\-dump\-config\fP
.RS 4
Displays the values of \fBspooler.cfg\fP configuration parameters and the
implied defaults.
.RE
.PP
\fB\-\-host\fR, \fB\-h\fR \fIpath\fR
.RS 4
Connect to the storage server through
\fIpath\fR, e.g.
file:///path/to/socket. Default:
file:///var/run/kopano/server.sock. Overrides the config file setting.
.RE
.PP
\fB\-\-foreground\fR, \fB\-F\fR
.RS 4
Run in the foreground. Normally the spooler will daemonize and run in the background.
.RE
.SH "USAGE"
.PP
To start the spooler delivering e\-mail to recipients:
.PP
\fBkopano\-spooler\fR
.PP
To start the spooler delivering e\-mail through
smtp.example.com:
.PP
\fBkopano\-spooler\fR
smtp.example.com
.PP
The spooler process will keep running and watching the outgoing queue for new mail to send. You may also use the init.d scripts:
.PP
\fB/etc/init.d/kopano\-spooler\fR
[\fIstart\fR|
\fIstop\fR|
\fIrestart\fR]
.SH "SIGNALS"
.PP
The following signals can be sent to the kopano\-spooler process:
.PP
\fBHUP\fR
.RS 4
When the HUP signal is received, some options from the configuration file are reloaded. The reloadable options are listed in the
\fBkopano-spooler.cfg\fR(5)
manual page.
.sp
Also, when using
\fIlog_method = file\fR, the logfile will be closed and a new logfile will be opened. You can use this signal in your logrotate system.
.RE
.PP
\fBTERM\fR
.RS 4
To gracefully let the service exit, the normal TERM signal is used. Because of multiple running threads, it may take up to 60 seconds for the server to completely shutdown.
.RE
.SH "AUTHOR"
.PP
Written by Kopano.
.SH "SEE ALSO"
.PP
\fBkopano-spooler.cfg\fR(5),
\fBkopano-server\fR(8)
