/*
 * SPDX-License-Identifier: AGPL-3.0-only
 * Copyright 2005 - 2016 Zarafa and its licensors
 */

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
//
#define IDD_SETTINGS_DLG                101
#define IDD_PROPPAGE_ADVANCE            102
#define IDD_AB_USERGENERAL_PAGE         103
#define IDD_PASSWORD_DLG                104
#define IDD_USERLISTDLG                 105
#define IDB_LOGO_KOPANO                 105
#define IDD_AB_DISTGENERAL_PAGE         106
#define IDD_SETTINGS_TAB_CONNECTION     107
#define IDD_AB_DISTMEMBEROF_PAGE        108
#define IDD_AB_USERORGANIZATION_PAGE    109
#define IDD_AB_USERPHONE_PAGE           110
#define IDD_AB_USERMEMBEROF_PAGE        111
#define IDD_AB_USEREMAIL_PAGE           112
#define IDD_AB_USEREMAIL_PAGE1          113
#define IDD_AB_DISTEMAIL_PAGE           113
#define IDD_CERTIFICATE_DLG             114
#define IDC_USERLIST                    202
#define IDI_KOPANO                      230
#define IDC_EDIT_SERVER                 1000
#define IDC_EDIT_SERVER_PORT            1001
#define IDC_EDIT_USERNAME               1002
#define IDC_EDIT_PASSWORD               1003
#define IDC_EDIT_PORT                   1004
#define IDC_TAB2                        1006
#define IDC_LIST1                       1007
#define IDC_LIST_MAILBOX                1007
#define IDC_DIST_LIST_MEMBERS           1007
#define IDC_DIST_MEMBEROF               1007
#define IDC_USER_MANAGER                1007
#define IDC_USER_NOTES                  1007
#define IDC_BUTTON1                     1008
#define IDC_BUTTON_ADD                  1008
#define IDC_B_MODIFY_MEMBERS            1008
#define IDC_BUTTON2                     1009
#define IDC_BUTTON_REMOVE               1009
#define IDC_BTN_VIEW_CERTIFICATE        1009
#define IDC_SSL                         1010
#define IDC_EDIT_SSL                    1011
#define IDC_USER_DISPLAY_NAME           1013
#define IDC_USER_EMAIL_TYPE             1014
#define IDC_DIST_ALIASNAME              1014
#define IDC_USER_ALIASNAME              1014
#define IDC_USER_DISPLAY_NAME2          1015
#define IDC_USER_EMAIL_ADDRESS          1015
#define IDC_DIST_DISPLAY_NAME           1016
#define IDC_LIST2                       1017
#define IDC_DIST_OWNER                  1017
#define IDC_USER_REPORTS                1017
#define IDC_L_USER_EMAIL_TYPE           1018
#define IDC_L_USER_DISPLAY_NAME         1019
#define IDC_L_USER_EMAIL_ADDRESS        1020
#define IDC_L_DIST_ALIASNAME            1021
#define IDC_L_DIST_DISPLAY_NAME         1022
#define IDC_EDIT1                       1024
#define IDC_USERNAME                    1024
#define IDC_E_PROXY_SERVER              1024
#define IDC_USER_FIRST_NAME             1024
#define IDC_USER_BUSINESS               1024
#define IDC_COMBO_CONNECTION_TYPE       1027
#define IDC_PASSWORD                    1030
#define IDC_CONNECT_TEXT                1033
#define IDC_S_USERNAME                  1034
#define IDC_S_PASSWORD                  1035
#define IDC_L_SERVER                    1036
#define IDC_L_PORT                      1037
#define IDC_L_USERNAME                  1038
#define IDC_L_PASSWORD                  1039
#define IDC_L_CONNECTION                1040
#define IDC_L_CONNECTION_TYPE           1041
#define IDC_L_SERVER_SETTINGS           1042
#define IDC_L_MAILBOX                   1043
#define IDC_CHECK_USE_PROXYSERVER       1044
#define IDC_CHECK_USE_PROXY_SERVER      1044
#define IDC_E_PROXY_PORT                1045
#define IDC_E_PROXY_USERNAME            1046
#define IDC_E_PROXY_PASSWORD            1047
#define IDC_CHECK_USE_COMPRESSION       1048
#define IDC_L_PROXY_SERVER              1050
#define IDC_L_PROXY_PORT                1051
#define IDC_L_PROXY_USERNAME            1052
#define IDC_L_PROXY_PASSWORD            1053
#define IDC_L_TIMEOUT                   1054
#define IDC_L_PROXY                     1055
#define IDC_E_TIMEOUT                   1056
#define IDC_BUTTON3                     1057
#define IDC_ANIMATE1                    1058
#define IDC_G_NAME                      1058
#define IDC_L_FIRST_NAME                1059
#define IDC_L_INITIALS                  1060
#define IDC_L_LAST_NAME                 1061
#define IDC_USER_INITIALS               1062
#define IDC_USER_LAST_NAME              1063
#define IDC_L_ADDRESS                   1066
#define IDC_L_CITY                      1067
#define IDC_L_STATE                     1068
#define IDC_L_ZIP_CODE                  1069
#define IDC_L_COUNTRY_REGION            1070
#define IDC_USER_ZIP_CODE               1071
#define IDC_USER_COUNTRY_REGION         1072
#define IDC_USER_STATE                  1073
#define IDC_USER_CITY                   1075
#define IDC_USER_ADDRESS                1076
#define IDC_USER_TITLE                  1077
#define IDC_USER_COMPANY                1078
#define IDC_USER_DEPARTMENT             1079
#define IDC_USER_OFFICE                 1080
#define IDC_USER_ASSISTANT              1081
#define IDC_USER_PHONE                  1082
#define IDC_L_TITLE                     1083
#define IDC_L_COMPANY                   1084
#define IDC_L_DEPARTMENT                1085
#define IDC_L_OFFICE                    1086
#define IDC_L_ASSISTANT                 1087
#define IDC_L_PHONE                     1088
#define IDC_L_DISPLAY_NAME              1090
#define IDC_L_ALIASNAME                 1091
#define IDC_L_OWNER                     1092
#define IDC_DIST_NOTES                  1094
#define IDC_L_NOTES                     1095
#define IDC_G_MEMBERS                   1096
#define IDC_L_GROUP_MEMBERSHIP          1097
#define IDC_L_MANAGER                   1098
#define IDC_L_DIRECT_REPORTS            1099
#define IDC_G_PHONE                     1101
#define IDC_L_BUSINESS                  1102
#define IDC_L_BUSINESS_2                1103
#define IDC_L_FAX                       1104
#define IDC_USER_FAX                    1105
#define IDC_USER_BUSINESS_2             1107
#define IDC_USER_HOME                   1108
#define IDC_USER_MOBILE                 1109
#define IDC_USER_PAGER                  1110
#define IDC_USER_HOME_2                 1111
#define IDC_L_HOME                      1112
#define IDC_L_HOME_2                    1113
#define IDC_L_MOBILE                    1114
#define IDC_L_PAGER                     1115
#define IDC_USER_MEMBEROF               1116
#define IDC_L_EMAIL_ADDRESSES           1117
#define IDC_USER_EMAIL_ADDRESSES        1118
#define IDC_L_ALIAS                     1119
#define IDC_EDIT2                       1120
#define IDC_DIST_EMAIL_ADDRESSES        1121
#define IDC_CHK_SAVE_CHOICE             1122
#define IDC_GRP_CERT_SUMMARY            1123
#define IDC_TXT_ISSUER                  1124
#define IDC_TXT_HOLDER                  1125
#define IDC_TXT_EXPIRATION              1126
#define IDC_VAL_ISSUER                  1127
#define IDC_VAL_HOLDER                  1128
#define IDC_VAL_EXPIRATION              1129
#define IDC_VAL_ERROR_DESCRIPTION       1130
#define IDC_TXT_HOSTNAME                1131
#define IDC_VAL_HOSTNAME                1132
#define IDC_STATIC_LOGO_KOPANO          1133

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1134
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
