SPOOLER_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

MAPI_CONFIG_PATH = ${SPOOLER_DIR}/../provider/client
PYTHONPATH = ${SPOOLER_DIR}/../swig/python/.libs:${SPOOLER_DIR}/../swig/python/
KOPANO_TEST_USER ?= user1
KOPANO_TEST_PASSWORD ?= user1
KOPANO_TEST_DAGENT_HOST ?= kopano_gateway
KOPANO_TEST_DAGENT_PORT ?= 2003
PYTEST ?= pytest


.PHONY: test
test:
	MAPI_CONFIG_PATH=${MAPI_CONFIG_PATH} PYTHONPATH=${PYTHONPATH}  \
	KOPANO_TEST_USER=${KOPANO_TEST_USER} KOPANO_TEST_PASSWORD=${KOPANO_TEST_PASSWORD} \
        KOPANO_TEST_DAGENT_HOST=${KOPANO_TEST_DAGENT_HOST} KOPANO_TEST_DAGENT_PORT=${KOPANO_TEST_DAGENT_PORT} \
	$(PYTEST) ${SPOOLER_DIR}/tests/ --junitxml=test.xml -o junit_suite_name=dagent
