#! /bin/sh

# Create a public store for the new company.

PATH=$PATH:/sbin:/usr/local/sbin:/usr/sbin

# The KOPANO_COMPANY variable from the server will always be in UTF-8
# format.  The --utf8 option must be set before this value is used,
# since the current locale isn't necessarily UTF-8.
kopano-admin -v --utf8 -s -I "${KOPANO_COMPANY}"
